[workspace]
resolver = "2"
members = [
    "crates/storage-core",
    "crates/storage-fs",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
publish = false

[workspace.dependencies]
async-trait = "0.1"
libc = "0.2"
storage-core = { version = "0.1.0", path = "crates/storage-core" }
tempfile = "3"
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt"] }
