[workspace]
resolver = "2"
members = [
    "crates/naust-storage-core",
    "crates/naust-storage-fs",
    "crates/naust-storage-s3",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT"

[workspace.dependencies]
async-trait = "0.1"
aws-sdk-s3 = { version = "1", default-features = false, features = ["behavior-version-latest", "default-https-client", "http-1x", "rt-tokio", "sigv4a"] }
bytes = "1"
libc = "0.2"
sha2 = "0.10"
naust-storage-core = { version = "0.1.0", path = "crates/naust-storage-core" }
tempfile = "3"
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt"] }
